<a href="https://colab.research.google.com/github/anwishn/ESAA/blob/main/0905_%EA%B3%BC%EC%A0%9C_%ED%8C%8C%EC%9D%B4%EC%8D%AC%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C_p_1_38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1단원. 파이썬 기반의 머신러닝과 생태계 이해

## 01. 머신러닝의 개념


---


**머신러닝(Machine Learning)** : 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 방법

-> 데이터를 기반으로 숨겨진 패턴을 스스로 인지하고 신뢰도 있는 예측 결과 도출

*   머신러닝의 분류

 + 지도학습(Supervised Learning)
 : <u>분류(Classification), 회귀(Regression)</u>, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석, NLP
 + 비지도학습(Un-supervised Learning)
 : 클러스터링, 차원 축소
 + 강화학습(Reinforcement Learning)

*   데이터 전쟁

 데이터 & 머신러닝 알고리즘 모두 중요한 요소
 but 머신러닝은 데이터에 의존적 => 최적의 데이터 더 중요


*   파이썬과 R 기반의 머신러닝 비교

 >+ R : 통계 전용 프로그램 언어 / 다양하고 많은 통계 패키지 보유
 >+ Python : 다양한 영역에서 사용되는 개발 전문 프로그램 언어
  
  + 파이썬이 R에 비해 뛰어난 점은?
  
      - 쉽고 뛰어난 개발 생산성 + 많은 라이브러리 + 뛰어난 확장성, 유연성, 호환성 + 다양한 애플리케이션 개발 가능 + 다양한 기업 환경으로의 확산 가능


## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지



---



* 머신러닝 패키지 : 사이킷런(Scikit-Learn)

* 행렬/선형대수/통계 패키지 : 넘파이(NumPy)

* 데이터 핸들링 : 판다스(Pandas)

* 시각화 : 맷플롯립(Matplotlib), 시본(Seaborn)

* 여러 서드파티 라이브러리


## 03. 넘파이


---


**NumPy**(Numerical Python) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

* 빠른 배열 연산 속도 보장

* C/C++과 같은 저수준 언어 기반의 호환 API 제공 (수행 성능이 중요한 부분은 C/C++기반 코드, 넘파이에서 이를 호출하는 방식)

* 다양한 데이터 핸들링 기능 제공(물론 판다스의 편리성 못 미침)


>### 넘파이 ndarray 개요
>* <u>import numpy as np</u> (넘파이 모듈 임포트)
>* 넘파이의 기반 데이터 타임 = ndarray

**array()** 함수 : 다양한 인자를 입력 받아 ndarray로 변환

**shape** 변수 : ndarray의 크기(행과 열의 수)를 튜플 형태로 가져 -> 배열의 차원까지 알 수 있어

**ndim** : ndarray의 차원

In [ ]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


>### ndarray의 데이터 타입
>* 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능
>* ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능

**dtype** 속성 : ndarray 내의 데이터 타입 확인


In [ ]:
list1 = [1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


* ndarray 내에 다른 데이터 유형이 섞여 있는 경우 => 데이터 타입이 더 큰 데이터 타입으로 형 변환

In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)  # int형이 문자열 값으로 변환

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)  # int형이 float형으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


 **astype()** 메서드 : ndarray 내 데이터값의 타입 변경

  + 대용량 데이터의 ndarray를 만들 때 사용되는 메모리를 더 절약해야 할 때 보통 이용

In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


>### ndarray를 편리하게 생성하기 - arange, zeros, ones
>* 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용

**arrange()** ≒ range()

 : array를 range()로 표현하는 것, 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarry의 데이터값으로 변환


In [ ]:
sequence_array = np.arange(10)   # default는 stop값 but start값도 부여 가능
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


**zeros()** : 튜플 형태의 shape값을 입력 => 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

**ones()** : 튜플 형태의 shape값을 입력 => 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환 

In [ ]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array = np.ones((3,2))                 # dtype 정해주지 않으면 default로 float64형의 데이터로 채워
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


> ### ndarray의 차원과 크기를 변경하는 reshape()
>**reshape()** 메서드 : ndarray를 특정 차원 및 크기로 변환
>* 변환을 원하는 크기를 함수 인자로 부여

In [ ]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)   # 2row 5col
print('array2:\n',array2)

array3 = array1.reshape(5,2)   # 5row 2col
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* 지정된 사이즈로 변경이 불가능하면 오류 발생

In [ ]:
array1.reshape(4,3)

ValueError: ignored

* 인자로 -1을 적용하는 경우 : 원래 ndarray와 호환되는 새로운 shape로 변환

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)       #5col에 맞는 row를 자동으로 새롭게 생성해 변환하라
print('array2 shape:',array2.shape)
array3 = array1.reshape(5,-1)       #5row에 맞는 col를 자동으로 새롭게 생성해 변환하라
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


* -1을 사용하더라도 호환될 수 없는 형태는 변환x

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: ignored

* -1인자는 reshape(-1,1)와 같은 형태로 자주 사용

     -> 여러개의 row를 가지되 반드시 1개의 col을 가진 ndarray로 변환됨을 보장 -> 결합할 때 형태 통일

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())       # tolist()메서드 : 리스트 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


> ### 넘파이의 ndarray의 데이터 세트 선택하기 - **인덱싱(indexing)**
>1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값 지정 -> 해당 위치의 데이터 반환
> 2. 슬라이싱(Slicing) : 연속된 인덱스상의 ndarray를 추출하는 방식, 시작 인덱스:종료 인덱스 = 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환
>3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정 -> 해당 위치에 있는 데이터의 ndarray 반환
>4. 불린 인덱싱(Boolean Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

>#### 단일 값 추출



In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

# 마이너스 기호 이용하여 맨 뒤에서부터 데이터 추출 가능
print('맨 뒤의 값:',array1[-1],', 맨 뒤에서 두 번째 값:',array1[-2])

# ndarray 내의 데이터값도 수정 가능
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 , 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]


* 다차원 ndarry에서 단일 값 추출 - 2차원의 경우 row와 col 위치의 인덱스를 통해 접근

   **row,col은 넘파이에서 사용x -> axis 0, axis 1이라 사용**

    <u>axis 0이 row 방향 축, axis 1이 col 방향 축</u>

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


> #### 슬라이싱

* ":" 기호 이용

* 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트 모두 ndarray 타입

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


* ":"사이의 시작, 종료 인덱스는 생략 가능

    시작 인덱스 생략 -> 처음 인덱스인 0으로 간주

    종료 인덱스 생략 -> 맨 마지막 인덱스로 간주

    시작/종료 인덱스 생략 -> 맨 처음/맨 마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


* 2차원 ndarray에서의 슬라이싱 - 1차원과 유사, row와 col인덱스를 지칭하는 부분만 차이

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2,0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3,0:3])
print('array2d[1:3, :] \n', array2d[1:3,:])
print('array2d[:, :] \n', array2d[:,:])
print('array2d[:2, 1:] \n', array2d[:2,1:])
print('array2d[:2, 0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


* 2차원 ndarray에서 뒤에 오는 인덱스 없애면 1차원 ndarray 반환 / 3차원 ndarray에서 뒤에 오는 인덱스 없애면 2차원 ndarray 반환

In [ ]:
print(array2d[0])   # axis 0(row축)의 첫 번째 row ndarray 반환
print(array2d[1])   # axis 0(row축)의 두 번째 row ndarray 반환
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


>#### 팬시 인덱싱

* 리스트나 ndarray로 인덱스 집합을 지정 -> 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d= array1.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


> #### 불린 인덱싱

* 조건 필터링과 검색 동시에 가능

* ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 기재 => True 값에 해당하는 index 값만 저장 => 저장된 index 값으로 데이터 조회

In [ ]:
array1d = np.arange(start=1,stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:',array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d > 5

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :',array4)

불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

>#### 행렬 정렬
>* **np.sort()** : 넘파이에서 sort() 호출
>  + <u>원 행렬은 그대로 유지</u> 한 채 원 행렬의 정렬된 행렬 반환
>* **ndarray.sort()** : 행렬 자체에서 sort() 호출
>  + <u>원 행렬 자체를 정렬</u> 한 형태로 변환하며 반환 값은 None

In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


* 기본적으로 오름차순 정렬 -> 내림차순 정렬 np.sort()[::-1] 

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


* 2차원 이상의 행렬 정렬 -> axis 축 값 설정 -> 로우 방향 또는 칼럼 방향으로 정렬 수행

In [ ]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


>#### 정렬된 행렬의 인덱스 반환하기
>**np.argsort()** : 정렬된 행렬의 인덱스를 ndarray 형으로 반환

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


* 내림차순 정렬 시에 원본 행렬의 인덱스 구하기 -> [::-1] 적용

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


* 넘파이에서 활용도 높다

In [ ]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

>#### 행렬 내적(행렬 곱)
>**np.dot()** 이용

In [ ]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


>#### 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
>**np.transpose()** 이용

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
