<a href="https://colab.research.google.com/github/anwishn/ESAA/blob/main/0916_%EA%B3%BC%EC%A0%9C_100_Numpy_exercises_26_39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

In [10]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [3]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))    # find common values

[0 3 4 5 6 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [11]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))    # 변수를 더 수학적으로 표현

np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [7]:
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')   # []안의 값에 따라 날짜 단위 지정 # D는 day / M은 month
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [33]:
A = np.ones(3) * 2
B = np.ones(3) * 4

np.add(A,B,out=B)       # A+B의 결과를 B에 할당
np.divide(A,2,out=A)    # A/2의 결과를 A에 할당
np.negative(A,out=A)    # -(A/2)의 결과를 A에 할당
np.multiply(A,B,out=A)  # (A+B)*(-A/2)와 같은 결과
print(A)

[-6. -6. -6.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [60]:
z = np.random.uniform(0,10,10)  # np.random.uniform(최소값, 최대값, 데이터 개수) : 균등분포 함수

print(z - z%1)   # 배열을 1로 나눈 나머지를 빼서 정수부분 구하기
print(z//1)

# 또 다른 방법
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[8. 8. 4. 6. 7. 1. 2. 9. 4. 5.]
[8. 8. 4. 6. 7. 1. 2. 9. 4. 5.]
[8. 8. 4. 6. 7. 1. 2. 9. 4. 5.]
[8. 8. 4. 6. 7. 1. 2. 9. 4. 5.]
[8 8 4 6 7 1 2 9 4 5]
[8. 8. 4. 6. 7. 1. 2. 9. 4. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [36]:
z = np.random.random(10)     # random vector 만들기
z.sort()
print(z)

[0.05282502 0.08553225 0.42068147 0.4801857  0.5428895  0.58322378
 0.62451097 0.63767554 0.85256283 0.91665651]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [61]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))
print(np.allclose(A,B))

False
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [42]:
z = np.random.random((10,2))
x, y = z[:,0],z[:,1]

# polar coordinates(distance r, angle seta)
r = np.sqrt(x**2+y**2)
angle = np.arctan2(y,x)   # y좌표, x좌표 순서로

print(r)
print(angle)

[0.90968114 0.71413814 0.22304926 0.9655125  1.00673137 1.20705304
 0.1335871  1.36236599 0.97341676 0.67272241]
[1.30403269 0.98955057 0.99700544 1.32203871 1.44443611 0.74502597
 1.54876786 0.80622464 0.98356873 0.075246  ]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [44]:
z = np.random.random(10)
z[z.argmax()] = 0   # np.argmax(z) # z.argmax() : max의 index
print(z)

[0.75702929 0.37526849 0.08140956 0.2740139  0.08001951 0.25931739
 0.73339166 0.6397749  0.71600033 0.81273242]
[0.75702929 0.37526849 0.08140956 0.2740139  0.08001951 0.25931739
 0.73339166 0.6397749  0.71600033 0.        ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [45]:
Z = np.arange(100)
v = np.random.uniform(0,100)

i = np.abs((Z-v)).argmin()
print(Z[i])

86


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [50]:
Z = np.arange(9).reshape(3,3)

# 배열을 인덱스하기 위한 다차원 반복자 객체
# np.ndenumerate()
for index,value in np.ndenumerate(Z):
  print(index,value)

# np.ndindex()
for index in np.ndindex(Z.shape):
  print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [51]:
n = 8  # array size
p = 5  # 놓을 원소 개수
Z = np.zeros((n,n))   # nxn 배열

# np.put(배열, 인덱스, 바꾸려는 값) : 배열의 지정된 요소를 주어진 값으로 치환
np.put(Z, np.random.choice(range(n*n), p, replace = False), 5)
print(Z)

[[0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [53]:
Z = np.random.randint(0,10,(3,3))
print(Z)

# column 1
print(Z[ Z[:,0].argsort() ])   # 1번째 열 성분을 기준으로 배열 정렬

[[2 8 7]
 [2 2 2]
 [1 1 8]]
[[1 1 8]
 [2 8 7]
 [2 2 2]]


In [54]:
Z = np.random.randint(0,10,(3,3))
print(Z)

# column 2
print(Z[ Z[:,1].argsort() ])   # 2번째 열 성분을 기준으로 배열 정렬

[[7 7 3]
 [4 7 9]
 [1 4 9]]
[[1 4 9]
 [7 7 3]
 [4 7 9]]


In [56]:
Z = np.random.randint(0,10,(3,3))
print(Z)

# column 3
print(Z[ Z[:,2].argsort() ])    # 3번째 열 성분을 기준으로 배열 정렬

[[0 0 7]
 [2 8 5]
 [6 7 8]]
[[2 8 5]
 [0 0 7]
 [6 7 8]]
