<a href="https://colab.research.google.com/github/anwishn/ESAA/blob/main/0916_100_Numpy_exercises_1_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
n = np.zeros((4,4))
print(n.size * n.itemsize)

128


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
v = np.zeros(10)
v[4]=1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(v[::-1])
print(np.flip(v))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [6]:
v = np.array([1,2,0,0,4,0])
print(np.where(v!=0))      # np.where() : 조건에 맞는 값의 인덱스 찾아줘
print(np.nonzero(v))

(array([0, 1, 4]),)
(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [7]:
np.identity(3)   # 정방단위행렬 NxN 가능
np.eye(3)        # 대각행렬 NxM 가능

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
np.random.random((3,3,3))

array([[[0.09004351, 0.73298134, 0.83571002],
        [0.760085  , 0.89935546, 0.03173651],
        [0.84496682, 0.60425931, 0.63009891]],

       [[0.4169665 , 0.29193689, 0.49634507],
        [0.67332126, 0.85389364, 0.14936529],
        [0.7215174 , 0.77581335, 0.98412354]],

       [[0.79043544, 0.25932168, 0.15853679],
        [0.00318229, 0.01721096, 0.10267914],
        [0.55665102, 0.79404062, 0.66079736]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
n = np.random.random((10,10))
print(n.min(),n.max())

0.01119743382846905 0.9973167809300743


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
n = np.random.random(30)
print(n.mean())

0.5184796545463861


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
n = np.ones((4,4))
n[1:-1,1:-1] = 0
print(n)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan은 '정의되지 않은 수' -> 비교하거나 연산 x
print(0 * np.nan)               # nan
print(np.nan == np.nan)         # False
print(np.inf > np.nan)          # False
print(np.nan - np.nan)          # nan
print(np.nan in set([np.nan]))  # True      # np.nan은 np.nan의 집합 내에 속한다
print(0.3 == 3 * 0.1)           # False     # 3 * 0.1 = 0.30000000000000004 != 0.3  # 부동소수점에 의한 오차

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
# np.diag 대각 행렬 함수 
# k를 지정하여 오른쪽/왼쪽으로 k칸 치우친 방향의 대각 성분도 획득 가능
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
# 1번째 방법
x = np.zeros((8,8),dtype=int)
# A:B:C # index A부터 index B까지 C의 간격으로 배열을 만들어라
x[1::2,::2] = 1  
x[::2,1::2] = 1  

print(x)

# 2번째 방법
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [8]:
Z = np.random.random((5,5))
Z = (Z-Z.mean())/Z.std()
print(Z)

[[ 0.40839098 -1.0357638  -0.8963542   0.27183498 -1.19197804]
 [ 0.61763074 -0.70995776 -0.66089083  1.37159945 -0.09336687]
 [ 1.63544039 -1.25821475  0.48127166 -0.46452687  0.06204522]
 [-0.89379169  1.71560588 -1.2008753   0.68289129  1.86110556]
 [-0.58607246  0.11851291 -1.27060314 -0.46123706  1.49730372]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("R",np.ubyte),("G",np.ubyte),("B",np.ubyte),("A",np.ubyte)])
print(color)

# data type의 축약형 중 u는 부호없는 정수, 각각의 색깔에 해당됨

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [9]:
M=np.arange(15).reshape(5,3)
N=np.arange(6).reshape(3,2)
print(np.dot(M,N))
print(M@N)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(12)
Z[ (3<Z) & (Z<8) ] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#np.sum(a,axis=None) # axis 축으로 더한다.

print(sum(range(5),-1))   # 0+1+2+3+4+(-1)
from numpy import *
print(sum(range(5),-1))   # 0+1+2+3+4

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z) # error

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [10]:
# array를 나누는 것은 x, 몫구하는 것은 o
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  
