<a href="https://colab.research.google.com/github/anwishn/ESAA/blob/main/0930_%EA%B3%BC%EC%A0%9C_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬머신러닝완벽가이드 p.87-131

# 2단원. 사이킷런으로 시작하는 머신러닝

## 01. 사이킷런 소개와 특징


---



**사이킷런(scikit-learn)** 

: 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리

: 파이썬 기반의 머신러닝을 위한 가장 쉽고 효율적인 개발 라이브러리 제공

* 특징

1) 쉽고 가장 파이썬스러운 API 제공

2) 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API 제공

3) 오랜 기간 실전 환경에서 검증, 매우 많은 환경에서 사용되는 성숙한 라이브러리

In [13]:
import sklearn

print(sklearn.__version__)    # 버전 확인

1.0.2


## 02. 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기


---



* 붓꽃 데이터 세트 -> 붓꽃의 품종 분류하기
* 붓꽃 데이터 피처 : Sepal length(꽃잎의 길이), Sepal width(꽃잎의 너비), Petal length(꽃받침의 길이), Petal width(꽃받침의 너비)
* 붓꽃 데이터 품종 : Setosa, Vesicolor, Virginica



**분류(Classification)** : 대표적인 지도학습 방법의 하나
* 지도학습

: 명확한 정답이 주어진 데이터를 먼저 학습 -> 미지의 정답을 예측

: 학습 데이터 세트(for 학습) + 테스트 데이터 세트(for 머신러닝 모델의 예측 성능 평가)



-모듈명은 sklearn으로 시작

**sklearn.datasets** : 사이킷런에서 자체적으로 제공하는 데이터 세트를 생성하는 모듈의 모임

**sklearn.tree** : 트리 기반 ML 알고리즘을 구현한 클래스의 모임

**sklearn.model_selection** : 학습 데이터와 검증 데이터, 예측 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 다양한 모듈의 모임

+) 하이퍼 파라미터 : 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터들을 통칭, 머신러닝 알고리즘의 성능 튜닝 가능

>* 붓꽃 데이터 세트 생성 = **load_iris()**
>* ML 알고리즘 = 의사 결정 트리 알고리즘 **DecisionTreeClassifier**
>* 학습 데이터와 테스트 데이터로 분리 = **train_test_split()**

* load_iris() 함수 이용해 붓꽃 데이터 세트 로딩 후, 피처들과 데이터 값이 어떻게 구성돼 있는 지 확인 위해 DataFrame으로 변환

In [14]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [15]:
import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처만으로 된 데이터를 numpy로 가지고 있다      # sepal length, sepal width, petal length, petal width
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있다    # 0(setosa), 1(versicolor), 2(virginica)
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 세트 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

1) 데이터 세트 분리 : 데이터를 학습용 데이터와 테스트용 데이터로 분리

* 학습용 데이터와 테스트용 데이터는 반드시 분리해야돼
* **train_test_split()** : 학습 데이터와 테스트 데이터를 test_size 파라미터 입력 값의 비율로 분할

In [16]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)        # 피처 데이터 세트, 레이블(결정 값) 데이터 세트, test_size, random_state

**test_size** : 전체 데이터 세트 중 테스트 데이터 세트의 비율

**random_state** : 호출할 때마다 같은 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값 => 수행할 때마다 동일한 데이터 세트로 분리
 + 숫자 자체는 어떤 값으로 지정해도 상관x, seed와 같은 의미

2) 모델 학습 : 학습 데이터를 기반으로 ML 알고리즘(의사 결정 트리)를 적용해 모델 학습

* 사이킷런의 의사 결정 트리 클래스 **DecisionTreeClassifier**를 객체로 생성
* 생성된 객체의 **fit()**메서드에 학습용 피처 데이터 속성(X_train)과 결정값 데이터 세트(y_train) 입력해 호출하면 학습 수행

In [17]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

3) 예측 수행 : 학습된 ML 모델을 이용해 테스트 데이터의 분류 예측

* 학습된 객체의 **predict()** 메서드에 테스트용 피처 데이터 세트(X_test) 입력해 호출하면 예측값 반환

In [18]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

4) 평가 : 예측된 결괏값과 테스트 데이터의 실제 결괏값 비교해 -> ML 모델(의사 결정 트리 기반의 DecisionTreeClassifier)의 예측 성능 평가

정확도(예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지) 평가 = **accuracy_score()**함수
* 첫 번째 파라미터로 실제 레이블 데이터 세트, 두 번째 파라미터로 예측 레이블 데이터 세트

In [19]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


## 03. 사이킷런의 기반 프레임워크 익히기

---



### Estimator 이해 및 fit(), predict() 메서드

* **지도학습**의 주요 두 축인 분류(Classification)와 회귀(Regression) 

   => ML 모델 학습 : fit(), 학습된 모델의 예측 : predict()

* Estimator 클래스 : 지도학습의 모든 알고리즘을 구현한 클래스 통칭
> + Classifier : 분류 알고리즘을 구현한 클래스
> + Regressor : 회귀 알고리즘을 구현한 클래스

* Estimator 클래스는 fit()과 predict()를 내부에서 구현

 + cross_val_score()(evaluation함수), GridSearchCV.fit()(하이퍼 파라미터 튜닝을 지원하는 클래스) 함수 내에서 이 Estimator의 fit()과 predict()를 호출해 평가하거나 하이퍼 파라미터 튜닝 수행


* **비지도학습**인 차원 축소, 클러스터링, 피처 추출 등

   => fit(), transform()

>* fit() : 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업  (지도학습의 fit()과 같이 학습 의미x)
>* transform() : 입력 데이터의 차원 변환, 클러스터링, 피처 추출 등의 실제 작업
>* fit_transform() : 이 둘을 하나로 결합
 + 별도로 호출할 필요 줄여줘 but 사용에 약간 주의

### 사이킷런의 주요 모듈

* 예제 데이터
>* sklearn.datasets : 사이킷런에 내장되어 예제로 제공하는 데이터 세트

* 피처 처리
>* sklearn.preprocessing : 데이터 전처리에 필요한 다양한 가공 기능 제공
>* sklearn.feature_selection : 알고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행하는 다양한 기능 제공
>* sklearn.feature_extraction : 텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는 데 사용        
(텍스트 -> sklearn.feature_extraction.text모듈, 이미지 -> sklearn.feature_extraction.image모듈)

* 피처 처리 & 차원 축소
>* sklearn.decomposition : 차원 축소와 관련한 알고리즘을 지원하는 모듈, PCA, NMF, Truncated SVD 등을 통해 차원 축소 기능 수행

* 데이터 분리, 검증 & 파라미터 튜닝
>* sklearn.model_selection : 교차 검증을 위한 학습용/테스트용 분리, 그리드 서치(Grid Search)로 최적 파라미터 추출 등의 API 제공

* 평가
>* sklearn.metrics : 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공

* ML 알고리즘
>* sklearn.ensemble : 앙상블 알고리즘 제공
>* sklearn.linear_model : 주로 회귀 관련 알고리즘을 지원. 또한 SGD 관련 알고리즘도 제공
>* sklearn.naive_bayes : 나이브 베이즈 알고리즘 제공
>* sklearn.neighbors : 최근접 이웃 알고리즘 제공
>* sklearn.svm : 서포트 벡터 머신 알고리즘 제공
>* sklearn.tree : 의사 결정 트리 알고리즘 제공
>* sklearn.cluster : 비지도 클러스터링 알고리즘 제공

* 유틸리티
>* sklearn.pipeline : 변환과 ML 알고리즘 학습, 예측 등을 함께 묶어서 실행할 수 있는 유틸리티 제공




* 머신러닝 모델을 구축하는 주요 프로세스
   : 피처 처리(feature processing) -> ML 알고리즘 학습 -> 예측 수행 -> 모델 평가

### 내장된 예제 데이터 세트

사이킷런에는 예제로 활용할 수 있는 데이터 세트 내장 - **datasets** 모듈에 있는 여러 API 호출

1) 분류나 회귀 연습용 예제 데이터

>* datasets.load_boston() : 회귀 용도, 미국 보스턴의 집 피처들과 가격에 대한 데이터 세트
>* datasets.load_breast_cancer() : 분류 용도, 위스콘신 유방암 피처들과 악성/음성 레이블 데이터 세트
>* datasets.load_diabetes() : 회귀 용도, 당뇨 데이터 세트
>* datasets.load_digits() : 분류 용도, 0에서 9까지 숫자의 이미지 픽셀 데이터 세트
>* datasets.load_iris() : 분류 용도, 붓꽃에 대한 피처를 가진 데이터 세트

* fetch계열의 명령 : 데이터 크기가 커 패키지에 처음부터 저장x 인터넷에서 내려받아 홈 디렉터리 아래의 scikit_learn_data라는 서브 디렉터리에 저장한 후 추후 불러들이는 데이터

  -> 최초 사용 시에 인터넷에 연결돼 있지 않으면 사용x

2) 분류나 클러스터링을 위한 표본 데이터 생성기

>* datasets.make_classifications() : 분류를 위한 데이터 세트 만들기. 특히 높은 상관도, 불필요한 속성 등의 노이즈 효과를 위한 데이터를 무작위로 생성
>* datasets.make_blobs() : 군집 지정 개수에 따라 클러스터링을 위한 데이터 세트를 무작위로 생성.


* 데이터 구성 : 딕셔너리 형태
* 키는 보통 data, target, target_name, feature_names, DESCR
>+ data : 피처의 데이터 세트
>+ target : 분류 시 레이블 값, 회귀일 때는 숫자 결괏값 데이터 세트
>+ target_names : 개별 레이블의 이름
>+ feature_names : 피처의 이름
>+ DESCR : 데이터 세트에 대한 설명과 각 피처의 설명

* data, target은 넘파이 배열(ndarray) 타입 / target_names, feature_names는 넘파이 배열 또는 파이썬 리스트(list) 타입 / DESCR은 스트링 타입

In [20]:
# 붓꽃 데이터 세트 생성
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))     # Bunch 클래스는 파이썬 딕셔너리 자료형과 유사

<class 'sklearn.utils.Bunch'>


In [21]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)     # 데이터 키는 피처들의 데이터 값 => 값 추출하려면 데이터 세트.data 또는 데이터 세트['data']

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [22]:
print('\n feature_names의 type:',type(iris_data.feature_names))
print(' feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print(' target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print(' data의 shpae:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print(' target의 shpae:', iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shpae: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5

## 04. Model Selection 모듈 소개


---

사이킷런의 **model_selection**모듈 : 학습 데이터와 테스트 데이터 세트를 분리하거나 교차 검증 분할 및 평가, 그리고 Estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스 제공

### 학습/테스트 데이터 세트 분리 - train_test_split()

In [25]:
# 학습 데이터 세트로만 학습하고 예측 시 문제점
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트으로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0


사이킷런의 **train_test_split()** : 원본 데이터 세트에서 학습 및 테스트 데이터 세트로 분리

* sklearn.model_selection 모듈에서 train_test_split 로드
* 첫 번째 파라미터로 피처 데이터 세트, 두 번째 파라미터로 레이블 데이터 세트(선택적으로 다음 파라미터 입력)
>+ test_size : 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할 것인가 결정. 디폴트는 0.25
>+ train_size : 전체 데이터에서 학습용 데이터 세트 크기를 얼마로 샘플링할 것인가 결정. 통상적으로 test_size 파라미터 사용.
>+ shuffle : 데이터를 분리하기 전에 데이터를 미리 섞을지 결정. 디폴트는 True.
>+ random_state : 호출할 때마다 동일한 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값. 
* 반환값은 튜플 형태. 순차적으로 학습용 데이터의 피처 데이터 세트, 테스트용 데이터의 피처 데이터 세트, 학습용 데이터의 레이블 데이터 세트, 테스트용 데이터의 레이블 데이터 세트 반환.


In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [27]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


### 교차 검증

알고리즘을 학습시키는 학습 데이터와 예측 성능을 평가하기 위한 별도의 테스트용 데이터 필요

but 테스트 데이터에만 최적의 성능을 발휘할 수 있도록 편향되게 모델 유도하는 경향 => 다른 테스트용 데이터 들어올 경우 성능 저하

**과적합(Overfitting)** : 모델이 학습 데이터에만 과도하게 최적화되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어지는 것

해결방안 => **교차 검증**

  : 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가 수행

  : 별도의 검증 데이터 세트를 둬 최종 평가 이전에 학습된 모델 다양하게 평가(<u>학습 데이터를 다시 분할</u>하여 학습 데이터 세트와 검증 데이터 세트로 나눠) 

#### K 폴드 교차 검증

**K 폴드 교차 검증** : 가장 보편적으로 사용되는 교차 검증 기법

  : K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행하는 방법

 : 데이터 세트를 K등분 => 처음부터 (N-1)개등분은 학습 데이터 세트, 마지막 K번째 등분 하나를 검증 데이터 세트로 설정 => 학습/검증 데이터 세트 점진적으로 변경하면서 학습과 평가 수행 => K개의 예측 평가 평균

* KFold 클래스

KFold(n_splits=K)으로 KFold 객체 생성

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


KFold 객체의 split() 호출

: K개의 폴드 데이터 세트로 분리

: 학습용/검증용 데이터로 분할할 수 있는 인덱스 반환, 교차 검증 시마다 검증 세트의 인덱스가 달라짐

In [31]:
n_iter=0

# KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1
  # 반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


#### Stratified K 폴드

**Stratified K 폴드** : 불균형한 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K 폴드 방식

: K 폴드가 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제 해결해줘

: 원본 데이터의 레이블 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습과 검증 데이터 세트 분배

* StratifiedKFold 클래스

In [32]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [35]:
kfold = KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


교차 검증 시마다 3개의 폴드 세트로 만들어지는 학습 레이블과 검증 레이블이 완전히 다른 값으로 추출

(학습 레이블은 1,2밖에 없으므로 0의 경우는 전혀 학습x, 검증 레이블은 0밖에 없으므로 학습 모델은 절대 0 예측x) 

=> 검증 예측 정확도는 0

=> StratifiedKFold는 KFold로 분할된 레이블 데이터 세트가 전체 레이블 값의 분포도를 반영하지 못하는 문제 해결

* 사용방법은 거의 비슷
* 차이 = split() 메서드에 인자로 피처 데이터 세트뿐만 아니라 레이블 데이터 세트도 반드시 필요하다

In [36]:
# 분포도가 레이블별로 동일하게 할당 -> 레이블 값 모두 학습 -> 검증 수행 가능
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증 : {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증 : 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증 : 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증 : 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [39]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  # 반복 시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:',np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


* 왜곡된 레이블 데이터 세트에서는 반드시 Stratified K 폴드 이용해 교차 검증
* 일반적으로 분류에서의 교차 검증 = Stratified K 폴드로 분할
* 회귀에서는 Stratified K 폴드 지원 x (<- 회귀의 결정값은 연속된 숫자값이므로 결정값별로 분포 정하는 의미x)

#### 교차 검증을 보다 간편하게 - cross_val_score()

**cross_val_score()** : 1) 폴드 세트 설정, 2) for루프에서 반복으로 학습 및 테스트 데이터의 인덱스 추출, 3) 반복적으로 학습과 예측 수행, 예측 성능 반환.. 이런 일련의 과정을 한꺼번에 수행해주는 API



```
cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_parms=None, pre_dispatch='2*n_jobs')
```
* estimator : 사이킷런의 분류 알고리즘 클래스 Classifier(Stratified K 폴드 방식으로 분할) 또는 회귀 알고리즘 클래스 Regressor(K 폴드 방식으로 분할)
* X : 피처 데이터 세트
* y : 레이블 데이터 세트
* scoring : 예측 성능 평가 지표
* cv : 교차 검증 폴드 수
* 반환값 = cv로 지정된 횟수만큼 scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환



In [41]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증별 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증별 정확도: 0.9667


* Estimator를 학습(fit), 예측(predict), 평가(evaluation)시켜줘 간단하게 교차 검증 수행 -> 내부적으로 StratifiedKFold 이용
* cross_val_score와 cross_validate() 비슷한 API(보통 cross_val_score() 하나로도 대부분의 경우 사용)
* cross_val_score()는 단 하나의 평가 지표만 가능 / corss_validate()는 여러 개의 평가 지표 반환 가능, 학습 데이터에 대한 성능 평가 지표와 수행 시간도 같이 제공


### GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에

하이퍼 파라미터 : 머신러닝 알고리즘을 구성하는 주요 구성 요소, 이 값을 조정해 알고리즘의 예측 성능 개선

사이킷런은 GridSearchCV API를 이용해 알고리즘에 사용되는 하이퍼 파라미터를 순차적으로 입력하면서 편리하게 최적의 파라미터를 도출할 수 있는 방안 제공

**GridSearchCV** : 교차 검증을 기반으로 이 하이퍼 파라미터의 최적 값을 찾게
* (장점) 사용자가 튜닝하고자 하는 여러 종류의 하이퍼 파라미터 다양하게 테스트하면서 최적의 파라미터 편리하게 찾아줘
* (단점) 수행시간이 상대적으로 오래 걸려

* GridSearchCV 클래스의 생성자로 들어가는 주요 파라미터
>+ estimator : classifier, regressor, pipeline 사용
>+ param_grid : key + 리스트 값을 가지는 딕셔너리. estimator의 튜닝을 위해 파라미터명과 사용될 여러 파라미터 값 지정
>+ scoring : 예측 성능을 측정할 평가 방법 지정. 보통은 사이킷런의 성능 평가 지표를 지정하는 문자열로 지정하나 별도의 성능 평가 지표 함수도 지정 가능
>+ cv : 교차 검증을 위해 분할되는 학습/테스트 세트의 개수 지정
>+ refit : 디폴트가 True. True로 생성 시 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator 객체를 해당 하이퍼 파라미터로 재학습



In [42]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [44]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개(cv)의 train, test set fold로 나누어 테스트 수행 설정
### refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재학습시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과(cv_results_)를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

주요 칼럼별 의미
* params 칼럼 : 수행할 때마다 적용된 개별 하이퍼 파라미터값
* rank_test_score : 하이퍼 파라미터별로 성능이 좋은 score 순위.
 + rank_test_score = 1 -> 최적 하이퍼 파라미터의 값 = best_params_ / 그때의 평가 결과 값 = best_score_ 속성에 기록
* mean_test_score : 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가 평균값


In [46]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


* refit=True(디폴트) -> GridSearchCV가 최적 하이퍼 파라미터로 Estimator를 학습해 best_estimator_로 저장

In [47]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


* 일반적으로 학습 데이터를 GridSearchCV를 이용해 최적 하이퍼 파라미터 튜닝을 수행한 뒤에 별도의 테스트 세트에서 이를 평가하는 것이 일반적인 머신러닝 모델 적용 방법

## 05. 데이터 전처리


---



**데이터 전처리(Data Preprocessing)** 은 사이킷런의 ML 알고리즘을 적용하기 전에 미리 처리

* 결손값, 즉 NaN, Null 값은 허용x -> 고정된 다른 값으로 변환해야돼, Null값을 어떻게 처리해야 할지는 경우에 따라 달라
* 문자열 값을 입력 값으로 허용x -> 모든 문자열 값은 인코딩돼서 숫자 형으로 변환해야돼
 + 문자열 피처는 일반적으로 카테고리형 피처와 텍스트형 피처

### 데이터 인코딩

대표적인 인코딩 방식 = 레이블 인코딩과 원-핫 인코딩



#### 레이블 인코딩

**레이블 인코딩(Label encoding)** : 카테고리 피처를 코드형 숫자 값으로 변환하는 것

* LabelEncoder 클래스로 구현
* LabelEncoder를 객체로 생성 후 fit()과 transform() 호출해 수행

In [48]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


* LabelEncoder 객체의 classes_ 속성값 = 0부터 순서대로 변환된 인코딩 값에 대한 원본값
* inverse_transform() = 인코딩된 값 다시 디코딩

In [49]:
print('인코딩 클래스:', encoder.classes_)
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


* 간단하게 문자열 값을 숫자형 카테고리 값으로 변환
* 숫자 값의 경우 크고 작음에 대한 특성 작용 => 특정 ML 알고리즘에서 가중치가 더 부여되거나 더 중요하게 인식할 가능성 발생

* 레이블 인코딩은 <u>선형회귀와 같은 ML 알고리즘에는 적용하지 않아야해</u> => 트리 계열의 ML 알고리즘에는 문제x

#### 원-핫 인코딩

**원-핫 인코딩(One-Hot Encoding)** : 행 형태로 돼 있는 피처의 고유 값을 열 형태로 차원을 변환한 뒤, 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식

+) 원-핫 : 여러 개의 속성 중 단 한 개의 속성만 1로 표시

* OneHotEncoder 클래스로 구현
* 주의할 점
>+ 1) OneHotEncoder로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환돼야 한다
>+ 2) 입력 값으로 2차원 데이터가 필요하다 


In [52]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
lables=encoder.transform(items)
# 2차원 데이터로 변환합니다
labels = labels.reshape(-1,1)

# 원-핫 인코딩 적용
oh_recoder = OneHotEncoder()
oh_recoder.fit(labels)
oh_labels = oh_recoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


**get_dummies()** : pandas에 있는 원-핫 인코딩 더 쉽게 지원하는 API. 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능

In [53]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링과 정규화

**피처 스케일링(feature scaling)** : 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업

대표적인 방법 = 표준화와 정규화

**표준화(Standardization)** : 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것

* 새로운 데이터는 원래 값에서 피처 x의 평균을 뺸 값을 피처 x의 표준편차로 나눈 값으로 계산

**정규화(Normalization)** : 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념

* 새로운 데이터는 원래 값에서 피처 x의 최솟값을 뺀 값을 피처 x의 최댓값과 최솟값의 차이로 나눈 값으로 변환(선형대수에서의 정규화 개념)
* 새로운 데이터는 원래 값에서 피처의 i번째 피처 값에 해당하는 크기를 합한 값으로 나눠줘. 즉 개별 벡터를 모든 피처 벡터의 크기로 나눠줘(사이킷런의 Normalizer모듈)


#### StandardScaler

**StandardScaler** : 표준화를 쉽게 지원하기 위한 클래스

* 사이킷런에서 구현한 RBF 커널을 이용하는 서포트 벡터 머신이나 선형 회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현 => 사전에 표준화 적용하는 것은 예측 성능 향상에 중요한 요소

In [54]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


* StandardScaler 객체 생성 후 fit()과 transform() 메서드에 변환 대상 피처 데이터 세트 입력하고 호출

In [56]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()
# StandardScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns = iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MInMaxScaler

**MinMaxScaler** : 데이터값을 0과 1 사이의 범위 값으로 변환(음수 값이 있으면 -1에서 1값으로 변환)

In [57]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler=MinMaxScaler()
# MinMaxScaler로 데이터 세트 변환. fit()과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점

Scaler 객체를 이용해 데이터의 스케일링 변환 시

fit() : 데이터 변환을 위한 기준 정보 설정 적용 / transform() : 설정된 정보 이용해 데이터 변환 / fit_transform() : 한번에 적용

* 주의 필요

Sclaer객체를 이용해 학습 데이터 세트로 fit()과 transform() 적용하면, 

**테스트 데이터 세트로 다시 fit()을 수행하지 않고 학습 데이터 세트로 fit()을 수행한 결과를 이용해 transform()변환 적용해야돼**

(<- 기준 정보가 서로 달라져)

In [58]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [59]:
# 학습 데이터 train_array부터 MinMaxScaler 이용해 변환

# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터 변환함. 원본 10->1로 변환됨
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:',np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [60]:
# 테스트 데이터 test_array 변환

# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됨
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환.
test_scaled = scaler.transform(test_array)

# test_array의 scale 변환 출력
print('원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


=> 학습 데이터와 테스트 데이터의 스케일링이 맞지 않음. 학습 데이터와 테스트 데이터의 서로 다른 원본값이 동일한 값으로 변환되는 결과 초래.

=> 테스트 데이터에 다시 fit()을 적용해서는 안 되며 학습 데이터로 이미 fit()이 적용된 Scaler 객체를 이용해 transform()으로 변환해야돼

In [61]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:',np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print('원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


* fit_transform()을 적용할 때도 테스트 데이터에서는 절대 사용해서는 안된다
* => **전체 데이터 세트에 스케일링을 적용한 뒤 학습과 테스트 데이터 세트로 분리하는 것이 바람직**